orgId: meridian-regulator
role: Regulator
actingParty: meridian-regulator-1::1220a14ca128063b8dc9d1ebb0bd22633be9f2168500f4dbc1ecaeb1855b14e5acf8
jsonApiUrl: https://ledger-api.validator.devnet.sandbox.fivenorth.io
dataDir: ./data/indexer
rebuild: false
httpPort: 4015
pollIntervalMs: 5000
